"""English Playback copy and semantic Bootstrap icon registry."""
COLORS = dict(background='#111925', panel='#192536', raised='#233247', border='#34455b',
              text='#e3ebf6', secondary='#a8b8cd', accent='#73c8b9', error='#f2ad91')
CAMERA_COLORS = ('#24576a', '#56447d', '#53632f', '#7a4c39', '#2c6262', '#6e405f')
MONTHS = ('January','February','March','April','May','June','July','August','September','October','November','December')
WEEKDAYS = ('Mo','Tu','We','Th','Fr','Sa','Su')
DAY_STATES = {'unknown':'not checked', 'empty':'confirmed empty', 'partial':'partial search',
              'error':'search error', 'present':'indexed recordings', 'cache':'local cache',
              'configuration':'camera time zone required'}
ACTIONS = {
    'archives': ('film', 'Recordings', 'Open recordings'),
    'play': ('play-fill', 'Play', 'Play recording'),
    'pause': ('pause-fill', 'Pause', 'Pause playback'),
    'stop': ('stop-fill', 'Stop', 'Stop playback and its downloads'),
    'back': ('arrow-counterclockwise', '−10 s', 'Go back 10 seconds'),
    'forward': ('arrow-clockwise', '+10 s', 'Go forward 10 seconds'),
    'previous': ('chevron-left', 'Previous', 'Show previous month'),
    'next': ('chevron-right', 'Next', 'Show next month'),
    'today': ('calendar3', 'Today', 'Show the current month'),
    'mute': ('volume-mute', 'Unmute', 'Unmute audio'),
    'sound': ('volume-up', 'Mute', 'Mute audio'),
    'zoom_in': ('zoom-in', 'Zoom in', 'Zoom in on the timeline without moving playback'),
    'zoom_out': ('zoom-out', 'Zoom out', 'Zoom out on the timeline without moving playback'),
    'original': ('download', 'Download original', 'Save the complete original archive outside the cache'),
    'export': ('scissors', 'Export selection', 'Export selection A–B as MKV at keyframe boundaries'),
    'settings': ('sliders', 'Settings', 'Show local camera and cache settings'),
    'refresh': ('arrow-repeat', 'Refresh', 'Refresh recording metadata for the visible dates'),
    'details': ('info-circle', 'Details', 'Show recording availability, freshness and limitations'),
    'next_record': ('skip-forward-fill', 'Next recording', 'Go to the next recording'),
    'navigation': ('layout-sidebar', 'Calendar', 'Show or hide the calendar and cameras'),
    'cancel': ('x-lg', 'Cancel', 'Cancel the current export'),
    'apply': ('check2', 'Apply', 'Save local settings and refresh this camera and day'),
    'goto': ('clock', 'Go to time', 'Go to the entered time on the selected date'),
}
ERRORS = {
    'timezone-required': 'Camera time zone required. Use Settings in Details; the display time zone is separate.',
    'configuration-apply-failed': 'Settings were not fully applied. Check playback.json and retry. Credentials are preserved.',
    'backend-detection-failed': 'Detection failed. See the ISAPI and CGI steps in Details; recording availability remains unknown.',
    'tracks-partial': 'Partial coverage: some tracks failed. Recordings from usable tracks are preserved.',
    'track-mismatch': 'The returned track differs from the requested track. See Details for both values.',
    'search-rejected': 'The camera rejected the recording search.',
    'search-count-invalid': 'The announced result count is invalid.',
    'html-error-page': 'The camera returned an HTML error page, even though HTTP reported success.',
    'html-login-page': 'The camera returned an HTML login page.',
    'html-response': 'HTML was received instead of the expected XML.',
    'xml-root-unexpected': 'Unexpected XML root. See the root and namespace in Details.',
    'xml-malformed': 'The response is not valid XML.',
    'xml-entities-forbidden': 'XML rejected: DTD or entity declarations are not allowed.',
    'soap-fault': 'The camera returned a SOAP fault.',
    'camera-application-error': 'The camera returned an application error. See Details.',
    'timezone-unavailable': 'Time zone data is missing. Install dependencies including tzdata, then reopen Recordings.',
    'ambiguous-time': 'This local time occurs twice during the DST transition and cannot be disambiguated yet.',
    'nonexistent-time': 'This local time does not exist during the spring DST transition.',
    'device-identity-required': 'Camera identity unavailable. Set a local revision in Settings and change it after replacement.',
    'device-changed': 'The camera changed since this search. Refresh the calendar.',
    'authentication-failed': 'Authentication rejected. Check saved credentials and playback permissions.',
    'temporarily-unreachable': 'Camera unreachable. Cached recordings remain available.',
    'unsupported': 'No supported recording API detected on this camera.',
    'no-recording-track': 'No recording track discovered.',
    'track-unavailable': 'Configured track unavailable. Check Settings.',
    'no-video': 'No indexed video at this time.',
    'coverage-unknown': 'Coverage is unconfirmed at this time. See search details.',
    'no-video-in-snapshot': 'The received snapshot does not include this time. The camera file may still be growing.',
    'end-of-coverage': 'End of available coverage. Use Next recording to continue.',
    'session-limit': 'Continuing in a new bounded session at the same archive time.',
    'archive-boundary-gap': 'The archives do not meet at this time. The gap or overlap is preserved.',
    'archive-too-large': 'Archive exceeds the local size limit. Adjust the limit and quota in playback.json.',
    'cache-full': 'Insufficient cache reserve or disk space. Stop playback or increase the quota.',
    'cache-in-use': 'Another Recordings window is using this cache. Close it before retrying.',
    'cache-key': 'This installation key cannot decrypt the local index.',
    'cache-version': 'The index is newer than this application. Use a different cache directory.',
    'dependency-missing': 'FFmpeg or ffprobe not found. Check dependencies and executable paths.',
    'native-unavailable': 'libVLC did not start. Check that python-vlc and VLC use the same architecture.',
    'native-timeout': 'The player stopped responding. Its session was stopped; you can retry.',
    'rate-unavailable': 'The player did not accept the selected speed. Playback stopped without changing your setting.',
    'seek-unavailable': 'The player did not confirm a new frame at the requested position.',
    'next-archive-pending': 'Waiting for the next archive to become playable.',
    'segment-timestamps': 'Transport timestamps could not be verified. Original archives are preserved.',
    'media-invalid': 'Incomplete or unreadable media. Refresh recordings to check finalization.',
    'video-codec-unsupported': 'This version supports H.264 and HEVC. The detected codec needs additional support.',
    'incomplete-download': 'Download interrupted. Partial bytes are not treated as a complete file.',
    'invalid-response': 'Unrecognized camera response. This does not establish that recordings are absent.',
    'invalid-media-response': 'The camera returned an error or login page instead of video.',
    'cgi-coverage-unconfirmed': 'CGI list received; this API does not confirm completeness or file end times.',
    'cgi-result-limit': 'Partial CGI list: a limit or pagination was detected.',
    'pagination-limit': 'Partial search: pagination limit reached.',
    'pagination-repeated': 'Partial search: the camera repeated a page.',
    'pagination-count': 'Partial search: announced and received counts differ.',
    'configuration-invalid': 'Invalid playback.json settings. Check the documented fields and values.',
    'index-view-limit': 'Too many recordings in this view. Select fewer cameras.',
    'credentials-unavailable': 'Cannot read saved cameras with the current key.',
    'export-exists': 'The destination or temporary file already exists. Choose a new name.',
    'export-not-ready': 'Receive the complete original archive before exporting it.',
    'export-interval': 'Select an A–B range contained within one received archive.',
    'export-timestamps': 'Exported timestamps could not be verified. Save the original or choose another range.',
    'export-failed': 'Export incomplete. Check destination permissions and free space.',
    'preparation-incomplete': 'Preparation interrupted. Only successfully produced ranges are playable.',
    'long-gop-progressive': 'A longer video segment requires a new playlist generation.',
    'prefix-insufficient': 'Waiting for enough media data to start playback.',
    'prefix-budget-exhausted': 'Prefix inspection limit reached; waiting for the complete file.',
    'download-ended-before-prefix': 'Download finished before a usable prefix was available; inspecting the complete file.',
    'mp4-metadata-after-media': 'MP4 metadata is not available before the video data; waiting for the complete file.',
    'mp4-layout-unsupported': 'This MP4 layout requires the complete file.',
    'container-requires-complete-file': 'This container requires the complete file.',
    'target-not-received': 'The requested time has not been received yet. Download continues.',
}
STATES = {'INITIALIZING':'Preparing player', 'IDLE':'Choose a camera, date and time',
    'STOPPED':'Playback stopped', 'LOADING':'Finding recording', 'DOWNLOADING':'Downloading recording',
    'PREPARING':'Preparing video', 'STARTING':'Opening player', 'SEEKING':'Loading preview…',
    'PREVIEW_LOADING':'Loading preview…', 'PREVIEW':'Preview',
    'PLAYING':'Recorded playback', 'PAUSED':'Paused', 'BUFFERING':'Buffering',
    'ENDED':'Playback ended', 'GAP':'No video', 'CONFIGURATION':'Local settings required',
    'ERROR':'Playback unavailable', 'FAILED':'Playback unavailable'}
TEXT = {'preview_times': 'Requested: {requested} · Preview: {actual}',
        'background_download': ' · downloading {received:.1f}/{expected:.1f} MiB',
        'frame_observation': 'Visible-frame observation recorded (F8). This includes your reaction delay.',
        'frame_observation_unavailable': 'No active playback session to annotate.',
        'cli_description': 'microSD recording player',
        'cli_camera': 'Saved database ID of the selected camera',
        'cli_fixture': 'Local synthetic demo, without reading camera credentials',
        'cli_date': 'Local date YYYY-MM-DD',
        'cli_day_only': 'Search only the selected day',
        'cli_day_requires_camera': '--day-only requires --camera to limit the search to one camera.',
        'error_fallback': 'Operation unavailable. Code: {reason}'}


def error_text(reason):
    return ERRORS.get(reason, TEXT['error_fallback'].format(reason=reason)) if reason else ''

TEXT.update({
    'next_jump': 'Jumping to next recording: +{seconds:.0f} seconds.',
    'configure_zone_tip': 'Configure the local time zone for C{cid}',
    'configure_zone': 'Configure time zone for C{cid}',
    'settings_identity': 'Local settings for C{cid} · saved database ID\nCamera and display time zones are separate.',
    'received_mib': ' · {size:.1f} MiB',
    'expected_mib': ' / {size:.1f} MiB',
    'window_title': 'Recordings — v0.2.11-dev',
    'footer_help': 'Hover or use Tab for help. Timeline: arrows ±10 s, +/− zoom. F8: mark a visible frame.',
    'development_notice': 'Development version · local validation pending',
    'recordings': 'Recordings',
    'initializing': 'RECORDINGS · initializing',
    'volume_help': 'Adjust volume from 0 to 100; arrow keys work too',
    'no_selection': 'Selection A–B: not selected',
    'applying': 'Applying settings',
    'fixture_label': 'LOCAL DEMO',
    'archive_label': 'RECORDINGS',
    'original_disabled': 'Select and receive an archive before saving it',
    'export_disabled': 'Select start A and end B within a received archive',
    'cancel_disabled': 'No export in progress',
    'availability': 'Availability of selected cameras',
    'calendar': 'Calendar',
    'details_export': 'Details / Export',
    'settings': 'Settings',
    'choose_camera': 'RECORDINGS\n\nChoose a camera and date.',
    'mark_a': 'A — start',
    'mark_b': 'B — end',
    'setting_backend': 'Active camera API',
    'setting_zone': 'Confirmed camera time zone (CGI)',
    'setting_track': 'Track / stream (blank = automatic)',
    'setting_revision': 'Local device revision',
    'setting_shift': 'Explicit local time correction (seconds)',
    'setting_display_zone': 'Display time zone',
    'setting_quota': 'Cache quota (GiB)',
    'cached_suffix': ' · local cache',
    'current_cached_suffix': ' · cached archive (next archive readiness is separate)',
    'unknown': 'unknown',
    'runtime_help': 'Camera and player processes use the Playback interpreter.',
    'day_only': 'Search limited to the selected day; other dates remain cached or unchecked.',
    'badge_help': 'A badge means recordings are indexed, not that the entire day is covered.',
    'unknown_duration_help': 'Unknown CGI duration appears as a point until the media is inspected.',
    'cache_help': 'The cache is an observed snapshot; the camera file may still grow.',
    'audio_help': 'Audio settings are preserved at every speed. Audio starts muted; use Unmute.',
    'export_help': 'Selection export remuxes MKV at keyframes; frame-accurate cuts are not guaranteed.',
    'active_camera': 'ACTIVE CAMERA',
    'calendar_cameras': 'Calendar cameras',
    'calendar_legend': 'C#: indexed video · *: local cache\n? not checked · ! error · … partial · — empty',
    'speed': 'Playback speed',
    'timeline_legend': 'Indexed ▬   Received ━   Playable ═   Unknown duration │   Background: see day status',
    'mark_help_suffix': ' of the export selection',
    'settings_help': 'Time correction applies only here.\nCamera settings and clock are unchanged.\n\nChange the revision after replacing a camera without a detectable serial number.\nPasswords stay in the existing database.',
    'python_label': 'Playback Python: ',
    'missing_icons': 'Missing icon resources: ',
    'no_next_recording': 'No later recording in this loaded month. Check the next month.',
    'save_selection': 'Export selection as MKV',
    'save_original': 'Download original archive',
    'fixture_settings': 'The local demo uses its own settings and cache.',
    'apply_search': 'Applying this camera’s settings; the day search will restart.',
    'previous_day': 'Show previous day',
    'next_day': 'Show next day',
    'mark_help_prefix': 'Mark current position as ',
    'applied': 'Settings applied. Search restarted for this camera and day; no reopening needed.',
    'search_time': '  Last search: ',
    'same_python': ' · same interpreter: ',
    'time_format': 'Enter a time in HH:mm:ss format.',
    'invalid_settings': 'Invalid settings: check time zones, correction and quota.',
    'mark_start': 'start',
    'mark_end': 'end',
    'export_pending': 'Export queued',
    'export_working': 'Exporting',
    'export_complete': 'Export saved with metadata',
    'export_cancelled': 'Export cancelled',
    'native_python': 'Observed native player: Python ',
    'applying_progress': 'Applying settings…',
})
