"""Centralized French labels and semantic Bootstrap icon registry."""
COLORS = dict(background='#111925', panel='#192536', raised='#233247', border='#34455b',
              text='#e3ebf6', secondary='#a8b8cd', accent='#73c8b9', error='#f2ad91')
CAMERA_COLORS = ('#24576a', '#56447d', '#53632f', '#7a4c39', '#2c6262', '#6e405f')

ACTIONS = {
    'archives': ('film', 'Enregistrements', 'Ouvrir les enregistrements'),
    'play': ('play-fill', 'Lire', 'Lire l’enregistrement'),
    'pause': ('pause-fill', 'Pause', 'Mettre en pause'),
    'stop': ('stop-fill', 'Arrêter', 'Arrêter la lecture et les téléchargements associés'),
    'back': ('arrow-counterclockwise', '−10 s', 'Reculer de 10 secondes'),
    'forward': ('arrow-clockwise', '+10 s', 'Avancer de 10 secondes'),
    'previous': ('chevron-left', 'Précédent', 'Afficher le mois précédent'),
    'next': ('chevron-right', 'Suivant', 'Afficher le mois suivant'),
    'today': ('calendar3', 'Aujourd’hui', 'Revenir au calendrier du mois actuel'),
    'mute': ('volume-mute', 'Son', 'Rétablir le son'),
    'sound': ('volume-up', 'Son', 'Couper le son'),
    'zoom_in': ('zoom-in', 'Zoom +', 'Agrandir l’échelle de temps, sans déplacer la lecture'),
    'zoom_out': ('zoom-out', 'Zoom −', 'Réduire l’échelle de temps, sans déplacer la lecture'),
    'original': ('download', 'Original', 'Conserver une copie de l’archive originale, hors du cache'),
    'export': ('scissors', 'Exporter la plage', 'Exporter la plage A–B en MKV, aux limites des images clés'),
    'settings': ('sliders', 'Réglages', 'Afficher les réglages locaux de la caméra et du cache'),
    'refresh': ('arrow-repeat', 'Actualiser', 'Relancer la recherche de métadonnées du mois visible'),
    'details': ('info-circle', 'Détails', 'Afficher les disponibilités, leur fraîcheur et les limites'),
    'next_record': ('skip-forward-fill', 'Prochain', 'Aller explicitement au prochain enregistrement'),
    'navigation': ('layout-sidebar', 'Calendrier', 'Afficher ou replier le calendrier et les caméras'),
    'cancel': ('x-lg', 'Annuler', 'Annuler l’export en cours'),
    'apply': ('check2', 'Appliquer', 'Enregistrer les réglages locaux et relancer la recherche de cette caméra/journée'),
    'goto': ('clock', 'Aller', 'Aller à l’heure saisie pour la date sélectionnée'),
}

ERRORS = {
    'timezone-required': 'Configuration du fuseau caméra requise. Utilisez Configurer dans Détails ; le fuseau d’affichage ne suffit pas.',
    'configuration-apply-failed': 'Réglages non appliqués complètement. Consultez le fichier playback.json et réessayez ; les identifiants sont conservés.',
    'backend-detection-failed': 'Détection non aboutie. Consultez dans Détails les étapes ISAPI et CGI ; aucune absence d’archives n’est déduite.',
    'tracks-partial': 'Couverture partielle : une ou plusieurs pistes ont échoué. Les archives des pistes utilisables sont conservées.',
    'track-mismatch': 'La piste retournée ne correspond pas à la piste demandée ; consultez les deux valeurs dans Détails.',
    'search-rejected': 'Recherche refusée par la réponse applicative de la caméra.',
    'search-count-invalid': 'Le nombre de résultats annoncé n’est pas un entier valide.',
    'html-error-page': 'La caméra a renvoyé une page HTML d’erreur (f404), même si le statut HTTP est 200.',
    'html-login-page': 'La caméra a renvoyé une page HTML de connexion.',
    'html-response': 'Réponse HTML reçue à la place du XML attendu.',
    'xml-root-unexpected': 'Racine XML inattendue pour cette étape ; consultez la racine et le namespace dans Détails.',
    'xml-malformed': 'Le corps reçu n’est pas un document XML valide.',
    'xml-entities-forbidden': 'XML refusé : déclaration DTD ou entité interdite.',
    'soap-fault': 'La caméra a renvoyé une faute SOAP.',
    'camera-application-error': 'La caméra a renvoyé un code d’erreur applicatif ; consultez Détails.',
    'timezone-unavailable': 'Base des fuseaux absente. Installez les dépendances, dont tzdata, puis rouvrez Enregistrements.',
    'ambiguous-time': 'Heure répétée lors du changement d’heure : la caméra ne permet pas encore de la désambiguïser.',
    'nonexistent-time': 'Cette heure locale n’existe pas le jour du passage à l’heure d’été.',
    'device-identity-required': 'Identité de caméra indisponible. Renseignez une révision locale dans Réglages (à changer après remplacement).',
    'device-changed': 'La caméra a changé depuis cette recherche. Actualisez le calendrier.',
    'authentication-failed': 'Authentification refusée. Vérifiez les identifiants enregistrés et les droits de lecture.',
    'temporarily-unreachable': 'Caméra injoignable. Les archives déjà en cache restent consultables.',
    'unsupported': 'API d’archives non reconnue sur cette caméra.',
    'no-recording-track': 'Aucune piste d’enregistrement découverte.',
    'track-unavailable': 'La piste configurée n’est pas disponible. Vérifiez Réglages.',
    'no-video': 'Aucune vidéo indexée à cet instant.',
    'coverage-unknown': 'Couverture non confirmée à cet instant. Consultez les détails de recherche.',
    'no-video-in-snapshot': 'L’export reçu ne contient pas cet instant. Le fichier caméra est peut-être encore en croissance.',
    'end-of-coverage': 'Fin de la couverture disponible. Utilisez Prochain pour choisir explicitement la suite.',
    'session-limit': 'Passage à une nouvelle session bornée, au même instant.',
    'archive-boundary-gap': 'Les archives ne se raccordent pas à cet instant. Le trou ou le chevauchement reste visible.',
    'archive-too-large': 'Cette archive dépasse la limite locale. Ajustez la limite et le quota dans playback.json.',
    'cache-full': 'Réserve de cache ou espace disque insuffisant. Arrêtez la lecture ou augmentez le quota.',
    'cache-in-use': 'Le cache est déjà utilisé par une fenêtre Enregistrements. Fermez-la avant de réessayer.',
    'cache-key': 'L’index local ne peut pas être déchiffré avec la clé de cette installation.',
    'cache-version': 'Version d’index plus récente que cette application. Utilisez un autre dossier de cache.',
    'dependency-missing': 'FFmpeg ou ffprobe introuvable. Vérifiez les dépendances et leurs chemins.',
    'native-unavailable': 'Le lecteur libVLC n’a pas démarré. Vérifiez python-vlc et VLC de même architecture.',
    'native-timeout': 'Le lecteur a cessé de répondre. Sa session a été arrêtée ; vous pouvez réessayer.',
    'rate-unavailable': 'Le moteur n’a pas accepté la vitesse choisie. La lecture est arrêtée sans changer ce réglage.',
    'seek-unavailable': 'Le moteur n’a pas confirmé la position demandée. Aucun autre instant n’est présenté comme la cible.',
    'media-invalid': 'Média incomplet ou non lisible. Actualisez les archives pour vérifier sa finalisation.',
    'video-codec-unsupported': 'Cette version traite H.264 et HEVC. Le codec détecté nécessite une adaptation.',
    'incomplete-download': 'Téléchargement interrompu. Les octets partiels ne sont pas considérés comme un fichier complet.',
    'invalid-response': 'Réponse caméra non reconnue ; cela ne signifie pas absence d’archives.',
    'invalid-media-response': 'La caméra a renvoyé une erreur ou une page de connexion au lieu de la vidéo.',
    'cgi-coverage-unconfirmed': 'Liste CGI reçue ; exhaustivité et fins des fichiers non garanties par cette API.',
    'cgi-result-limit': 'Liste CGI partielle : limite ou pagination détectée.',
    'pagination-limit': 'Recherche partielle : plafond de pagination atteint.',
    'pagination-repeated': 'Recherche partielle : la caméra a répété une page.',
    'pagination-count': 'Recherche partielle : le nombre annoncé ne correspond pas aux éléments reçus.',
    'configuration-invalid': 'Configuration playback.json invalide. Vérifiez les champs et valeurs documentés.',
    'index-view-limit': 'Trop d’archives dans cette vue. Réduisez le nombre de caméras filtrées.',
    'credentials-unavailable': 'Impossible de lire les caméras enregistrées avec la clé actuelle.',
    'export-exists': 'Le fichier ou son fichier temporaire existe déjà. Choisissez un nouveau nom.',
    'export-not-ready': 'L’archive originale doit être entièrement reçue avant son export.',
    'export-interval': 'Choisissez une plage A–B entièrement comprise dans l’archive reçue.',
    'export-timestamps': 'Les bornes du média exporté ne sont pas vérifiables. Conservez l’original ou choisissez une autre plage.',
    'export-failed': 'Export non terminé. Vérifiez les droits et l’espace du dossier choisi.',
    'preparation-incomplete': 'Préparation interrompue : seules les plages effectivement produites sont lisibles.',
    'long-gop-progressive': 'Segments trop longs pour ce mode progressif. Cette source nécessite une qualification supplémentaire.',
}

STATES = {'INITIALIZING':'Préparation du lecteur', 'IDLE':'Choisissez une caméra, une date et une heure',
    'STOPPED':'Lecture arrêtée', 'LOADING':'Recherche de l’archive', 'DOWNLOADING':'Téléchargement de l’archive',
    'PREPARING':'Préparation de la vidéo', 'STARTING':'Ouverture du lecteur', 'SEEKING':'Recherche de la position',
    'PLAYING':'Lecture d’archives', 'PAUSED':'En pause', 'BUFFERING':'Mise en mémoire tampon',
    'ENDED':'Fin de lecture', 'GAP':'Aucune vidéo', 'CONFIGURATION':'Configuration locale requise',
    'ERROR':'Lecture indisponible', 'FAILED':'Lecture indisponible'}


def error_text(reason):
    return ERRORS.get(reason, 'Opération indisponible. Code : '+reason) if reason else ''
